### ISSUE TITLE
Add badge hacktoberfest-accepted

### ISSUE THREAD

**Issue by AbhishekMaira10** [fnplus/HACKTOBERFEST-2020-flutter-interview-questions#22]
There has been an update regarding hacktoberfest to reduce spam. It only accepts valid PR's
PRs count if:
Submitted in a repo with the hacktoberfest topic AND
during the month of October AND (
  The PR is merged OR
  The PR is labelled as hacktoberfest-accepted by a maintainer OR
  The PR has been approved
)

find out more at - https://hacktoberfest.digitalocean.com/hacktoberfest-update

**Comment by imabhishekkumar** [comment]
Thank you for the update, Noted!
