### ISSUE TITLE
Submit Flutter Interview Question with Answer

### ISSUE THREAD

**Issue by imabhishekkumar** [fnplus/HACKTOBERFEST-2020-flutter-interview-questions#4]

**Comment by jnvee** [comment]
Hello, this is my first time contributing @imabhishekkumar  and i want to contribute to this. Can you please make me an assignee ? I have both Questions and Answers on Flutter!

**Comment by MoyinShabi** [comment]
Hello, can you please assign me to this issue also?

**Comment by imabhishekkumar** [comment]
@jnvee Done. Happy contributing!

**Comment by MoyinShabi** [comment]
Can you please assign me to this also?😊

**Comment by imabhishekkumar** [comment]
Sure. @MoyinShabi

**Comment by MoyinShabi** [comment]
thank you!

**Comment by jnvee** [comment]
Hey I added 3 new questions. Please check my PR. Thanks!

**Comment by Sakshi725744** [comment]
@imabhishekkumar can i be assigned too for this job

**Comment by imabhishekkumar** [comment]
Assigned @Sakshi725744 .

**Comment by Sakshi725744** [comment]
Thanks. I added my share of questions please check

**Comment by CODE-REDux** [comment]
@imabhishekkumar I am really eager to contribute, can you assign this to me  also

**Comment by Tusar6701** [comment]
@imabhishekkumar I really want to contribute to this issue, can you please assign this to me?
